C/C++ typedef syntax detection improvement
sublimehq/Packages pull request #2941
Opened 2021-08-08 20:43 UTC by dannftk

`typedef`s of `struct|class|enum|union` are detected wiser, target defined types are recognized as types rather than nothing

Changes are applied to C, C++, ObjC, ObjC++ syntaxes

2021-08-12 06:31 UTC, dannftk commented
Is anyone to react on the PR?

2021-08-12 07:24 UTC, rchl commented
When the ST developer has time, he will come and merge multiple PRs in one swipe.
It's not uncommon for PRs to hang for months before that happens though so be patient.

In the meantime, if you want to use your changes, your best bet is too have local override for that syntax.

2021-08-16 06:35 UTC, dannftk commented
How to request someone to run CI on the PR?

2021-08-18 08:52 UTC, deathaxe requested changes
The intention of my request is to keep fragmentation of test cases low. Maybe already too late in some syntaxes, I know.

Otherwise I find it a simple but effective improvement.

2021-08-18 08:52 UTC, deathaxe commented on C++/syntax_test_c.c
> +typedef struct MyStructure {} MyStructure_t;
I'd try to keep test cases logically grouped. So moving this one before or after the one in line 290 would be suitable.

2021-08-18 08:52 UTC, deathaxe commented on C++/syntax_test_cpp.cpp
> +typedef struct MyStructure {} MyStructure_t;
The same here. There's a test case at line 410, which this one could moved to for better grouping. The current one at 410 could also be tweaked to test your change.

2021-08-20 09:38 UTC, deathaxe submitted a review, later dismissed

2021-08-20 10:17 UTC, dannftk commented
@deathaxe, I've done everything how you asked me to do

2021-08-20 10:24 UTC, deathaxe approved these changes

2021-09-12 10:39 UTC, keith-hall approved these changes

2021-09-12 11:28 UTC, merged