C/C++ syntax improvement: bring out numeric constants in variables section
sublimehq/Packages pull request #2960
Opened 2021-08-15 19:05 UTC by dannftk

2021-08-16 06:35 UTC, dannftk commented
How to request someone to run CI on the PR?

2021-08-16 09:26 UTC, rwols commented
> How to request someone to run CI on the PR?

Some maintainer needs to click a button.

Or: a maintainer can edit the repo settings to automatically run the CI for users whose account is older than X days. It is currently disabled for all first-time contributors, which is too strict.

2021-08-17 19:52 UTC, deathaxe commented on C++/C++.sublime-syntax
> +    - match: '{{hex_integer}}'
By moving those patterns to variables its just harder to keep track of capture groups.

The only reason to introduce variables was to provide an easier way for an inherited syntax to tweak those patterns without touching contexts. 

But I guess that's not scope of this PR.

2021-08-18 08:57 UTC, deathaxe requested changes
Would you mind adding some test cases which cover your code changes, please, so we can make sure to not break those by possible future changes?

2021-08-20 09:38 UTC, deathaxe approved these changes

2021-08-20 10:13 UTC, dannftk commented
How do I request one more reviewer to glance at the PR?

2021-09-09 00:01 UTC, jfcherng approved these changes

2021-09-09 15:36 UTC, merged