[Markdown] Add support for LaTeX math blocks
sublimehq/Packages pull request #3397
Opened 2022-05-21 17:24 UTC by deathaxe

Closes #3251

2022-05-21 23:15 UTC, jrappen submitted a review, later dismissed

2022-05-23 21:00 UTC, jrappen submitted a review, later dismissed

2022-05-24 09:15 UTC, FichteFoll requested changes

2022-05-24 09:15 UTC, FichteFoll commented on Markdown/tests/syntax_test_markdown.md
> +# TEST: LATEX EQUATIONS #######################################################
Please add a test for an unclosed inline math expression that is not highlighted.

And one for the requirement of no whitespace on the inner boundaries of the enclosing punctuation, i.e. `$ 1 + 3 $`.

2022-05-24 10:15 UTC, deathaxe commented on Markdown/Markdown.sublime-syntax
> +    - meta_scope:
Maybe we need to distinguish those blocks with fenced-codeblock style standalone `$$` and those which look like inlines `$$ 1+1 $$`.

2022-05-24 14:40 UTC, jwortmann commented on Markdown/Markdown.sublime-syntax
> +    - meta_scope:
+1 for treating fenced-codeblock style `$$` and inline-style `$$` LaTeX blocks differently.

Interestingly, rendering on GitHub doesn't follow it's own specs as described in the [GitHub docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-expressions-as-blocks):

> To add a math expression as a block, **start a new line** and delimit the expression with two dollar symbols `$$`.

but it is also rendered as a LaTeX *block* on GitHub if there is preceding text (i.e. no new line) and following text:

```md
Some text $$\sqrt{2\pi}$$ more text
```
Some text $$\sqrt{2\pi}$$ more text

... while this PR recognizes it as inline math

![pic1](https://user-images.githubusercontent.com/6579999/170062650-f7ff338c-6d22-4cb0-8e63-d580fae67cbf.png)

2022-05-24 14:53 UTC, jwortmann commented
I wonder whether the following can be improved ([according to docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-dollar-signs-in-line-with-and-within-mathematical-expressions), `span` tags should disable parsing the `$` as LaTeX delimiter):

```md
<span>$</span>100 this is not LaTeX math \sqrt{2\pi} <span>$</span>200
```

Rendered on GitHub as:

<span>$</span>100 this is not LaTeX math \sqrt{2\pi} <span>$</span>200

Highlighting from this PR:

![pic2](https://user-images.githubusercontent.com/6579999/170065751-b2e16533-c215-496d-8565-581bb39ccbe3.png)

Perhaps the `<span>` tag should be treated specially, to ignore the LaTeX delimiter? Or maybe would it be enough to adjust the priority of included contexts? (I haven't really looked at the implementation)

Interestingly, the highlighting is not affected if the 2nd `$` isn't enclosed in a `span` tag:

![pic3](https://user-images.githubusercontent.com/6579999/170065770-9fdb8c5e-ccb2-4b9c-b881-6d25b01dc9a5.png)

2022-05-24 16:27 UTC, deathaxe commented
Current PR is part of MDE for years without any complains. I am uncertain about how much effort we should invest into such uncommon odd edge cases with regards to resulting complexity readability. Starting to push contexts for inline html tags is very likely to not play well with emphasises at some point. Things get worth if we want to fail on paragraph ends, I guess.

2022-05-25 08:11 UTC, jrappen submitted a review, later dismissed

2022-05-25 09:21 UTC, deathaxe commented
Maybe worth digging into it a bit deeper to improve some edge cases.

2022-05-28 15:14 UTC, jwortmann commented
Pretty neat that the last commit solves the problem with `<span>$</span>`, but I fear to reject everything that looks like a HTML tag is not the best approach. The following example with a "smaller than" operator breaks syntax highlighting further down the file (I would say it is not very uncommon to have no whitespace around operators or other symbols in LaTeX):

```markdown
Some text with $a<b$ inline math

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

![Unbenannt](https://user-images.githubusercontent.com/6579999/170831298-152ea1dd-7fa3-4ae3-b796-cf68f01d43be.png)

Rendering on GitHub does still have some similar issues as well: https://github.com/github/feedback/discussions/17022

2022-05-28 15:30 UTC, deathaxe commented
I guess we could play that game forever. There are just too many ambiguities in Markdown, which can barely handled by a lexer which needs to get all things done in one cycle.

Just consider start or end of bold/italics in the middle of equations, which causes them to not be rendered. `*text $1*2$` (*text $1*2$). I doubt we want/can handle them all.

2022-05-28 15:43 UTC, jwortmann commented
True. But I guess the more of critical edge cases which may break syntax highlighting we can find and improve now, the less bug reports will appear after this is merged and released.

2022-05-28 16:14 UTC, michaelblyons commented
> Just consider start or end of bold/italics in the middle of equations, which causes them to not be rendered. `*text $1*2$` (_text $1_2$). I doubt we want/can handle them all.

And furthermore, I doubt they are interpreted consistently in parsers that _do_ support MathJax.

2022-05-28 16:17 UTC, deathaxe commented
MathJax expressions are rendered by browser. Each markdown parser just handles it as plain text thus bold/italics/htmltags have higher priority - each causing the equation to render invalid.

Main issue is it being hard up to impossible to immitate those multiple cycles of parsing markdown in a single run using ST's syntax engine.

2022-05-31 00:37 UTC, FichteFoll commented on Markdown/Markdown.sublime-syntax
> +    - meta_scope:
Thanks for the clarification. Imo, if inline `$$` is supported in some fashion (like it apparently is by GitHub), we should have separate matchings for the inline and the block version, but if it's not exactly documented then it's not a requirement from my side. Feel free to resolve if deemed unnecessary.

2022-06-24 16:40 UTC, deathaxe commented
Synced source with MarkdownEditing 3.1.5

2022-06-26 14:17 UTC, jwortmann commented on Markdown/Markdown.sublime-syntax
> +    - meta_scope:
Looks like this has been implemented and can be marked as resolved now.

2022-06-26 14:19 UTC, jwortmann commented
Is it ready for review?

2022-06-27 07:51 UTC, FichteFoll commented
Unfortunately, the force-pushes make the PR rather hard to follow as it isn't as trivial to immediately spot the new changes in the new commits. GitHub provides a comparison link for the previous and new commits, but especially when merge commits or rebases are involved, it becomes non-trivial to detect these.

Since the PRs are getting squashed anyway, I believe it would be best to not rebase and force-push PRs instead of merging in master and adding more commits with fixes, especially when in response to review comments.

2022-06-27 07:59 UTC, FichteFoll submitted a review, later dismissed

2022-06-27 16:23 UTC, deathaxe commented
I started with mergin master in, but found changes significant enough (due to branching) to be easier looked at as a whole. Sure context to previous changes was lost.

2022-06-30 18:28 UTC, jrappen commented on Markdown/Markdown.sublime-syntax
> +        # arbritary number of chars, maybe escaped dollar sign, but no html tags
typo

2022-06-30 18:31 UTC, jrappen commented on Markdown/Markdown.sublime-syntax
> +    # (workaround for sublimehq/sublime_text/issues/5415)
if you put the full URL, we can just right-click & open URL in browser from within Sublime

2022-06-30 18:31 UTC, jrappen commented
Code seems fine from a once-over. Comments had typos.

2022-07-01 18:03 UTC, jrappen approved these changes

2022-07-02 17:35 UTC, FichteFoll approved these changes

2022-07-03 16:50 UTC, michaelblyons approved these changes

2022-07-03 17:31 UTC, merged