[HTML] Fix html completion not working prior to tag
sublimehq/Packages pull request #3468
Opened 2022-08-10 21:31 UTC by jwortmann

Fixes #3467 regression introduced in https://github.com/sublimehq/Packages/commit/9e35426d39030880ddf952caab000ec7a5eadf24.

2022-08-10 23:06 UTC, michaelblyons approved these changes

2022-08-11 01:13 UTC, jfcherng approved these changes

2022-08-11 14:02 UTC, michaelblyons commented
Just wait until we find out that someone has made an extension of HTML that sometimes has two-char tag openings. 😛

2022-08-12 14:49 UTC, deathaxe requested changes
This change might trigger snippets in "tag-name" position which causes us to end up in double `<<`. 

![Animation](https://user-images.githubusercontent.com/16542113/184380731-81bede73-a829-448a-a756-26dc7eaeb0b6.png)

2022-08-12 15:25 UTC, deathaxe approved these changes
The issue mensioned before seems triggered by prior statement in the method.

2022-08-12 15:25 UTC, merged