[ActionScript] refactor syntax
sublimehq/Packages pull request #3558
Opened 2022-11-13 22:29 UTC by jrappen

- update to syntax v2
- add variables
- move comments to prototype context
- add named contexts for strings & comments while making use of `meta_scope`
- replace `captures: 0: ...` with `scope: ...`
- add more tests
- add completions
- add metadata file

Co-authored-by: Michael B. Lyons <michaelblyons@users.noreply.github.com>
Co-authored-by: deathaxe <deathaxe@users.noreply.github.com>

2022-12-08 18:53 UTC, deathaxe requested changes

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +      scope: keyword.control.actionscript
How about a dedicated `keywords` context to apply more detailed scopes such as `keyword.control.conditional` or `keyword.control.loop` ... just to get those inline with other syntaxes?

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +      scope: keyword.operator.symbolic.actionscript
Same here. While `keyword.operator.symbolic` is neat with regards to distinguish those from word-like operators, it doesn't follow currently applied scopes of all other syntaxes. Would be a good chance to change that.

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +  block-comment-basic:
Do you expect other kinds of block comments? Otherwise distinction between block and line would be probably enough.

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    - meta_scope: string.quoted.double.actionscript
Just to follow common string scoping ...

```suggestion
    - meta_scope: meta.string.actionscript string.quoted.double.actionscript
```

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    - meta_scope: string.quoted.single.actionscript
Just to follow common string scoping ...

```suggestion
    - meta_scope: meta.string.actionscript string.quoted.single.actionscript
```

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +        4: constant.numeric.suffix.actionscript
We probably don't want to include sign in numbers as it is not clear whether they can be distinguished from operators in all situations. The choosen `constant.numeric.sign` scope wouldn't be the appropriate one anyway.

```suggestion
    - match: (0[xX])(\h*)(L|l|UL|ul|u|U|F|f)?
      scope: meta.number.integer.hexadecimal.actionscript
      captures:
        1: constant.numeric.base.actionscript
        2: constant.numeric.value.actionscript
        3: constant.numeric.suffix.actionscript
```

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +      captures:
Does it make sense to try to distinguish floats from integers?

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +          ({{constant_numeric_exponent}})?
Exponent is used once only. Is it really worth a variable then?

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +      scope: support.constant.actionscript
There's another  `\b(?:{{constants}})\b` pattern in `main` context. I'd suggest to create a dedicated `language-constants` context to group all kinds of known/predefined constants.

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    )
Such a `language-constants` context could apply more detailed scopes such as `constant.language.[boolean|null]`.

2022-12-08 18:53 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +      [-+]??
Lazy matching `??` shouldn't be needed.

2022-12-08 18:54 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +##[ Variables ]#########################################################################################################
Can we aggree on a common section separator style across all syntaxes?

```suggestion
##[ VARIABLES ]################################################################
```

2022-12-08 19:03 UTC, deathaxe commented on ActionScript/ActionScript.sublime-build
> +    ],
A file pattern which contains a glob of the file extension which is already assigned to the syntax behind `selector` key seems redundant.

2022-12-08 19:04 UTC, deathaxe commented on ActionScript/ActionScript.sublime-build
> +    "cancel": { "kill": true },
I read the docs as `cancel` key to be needed only for custom build targets, which is not the case here.

2022-12-08 19:04 UTC, deathaxe commented on ActionScript/ActionScript.sublime-build
> +    "cmd": [
Most other build systems start with the command to run. Maybe this one should do that as well?

2022-12-08 19:08 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +##[ Variables ]#########################################################################################################
Sorry, 3. This is what all other syntaxes use.

2022-12-10 09:55 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    )
Not of a high priority, but I think such small lists of tokens could be one-liners:

```suggestion
    (?x: Boolean | Number | String | Void )
```

2022-12-10 09:55 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    )
```suggestion
    (?x: [eE] [-+]? \d+ )
```

2022-12-10 09:55 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    )
Maybe also add space around pipes and sort by capital/non-captial letters (U, u)

```suggestion
    (?x: L | l | UL | ul | U | u | F | f )
```

2022-12-10 09:55 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    - match: \b(?:{{classes}})\b
As all variables are groups already wrapping them into another one is not really needed.

```suggestion
    - match: \b{{classes}}\b
```

_Note: Applies to functions, keywords, types as well._

2022-12-10 09:55 UTC, deathaxe commented on ActionScript/ActionScript.sublime-syntax
> +    - match: \b(?:instanceof)\b
```suggestion
    - match: \binstanceof\b
```

2025-02-12 17:11 UTC, deathaxe commented
Sure it makes sense to put effort in this dead syntax? It died together with Flash.

2025-02-13 16:25 UTC, deathaxe submitted a review, later dismissed
LGTM!

2025-02-13 21:24 UTC, michaelblyons commented on ActionScript/ActionScript.sublime-completions
> +            "contents": "class ${1:className} extends ${2:superCLass} {\n\t${0:// statement(s);}\n}",
`superCLass`?

2025-02-14 12:47 UTC, michaelblyons approved these changes

2025-02-14 16:57 UTC, deathaxe approved these changes

2025-02-14 16:58 UTC, merged