[Common] Add git conflict marker highlighting
sublimehq/Packages pull request #4047
Opened 2024-09-29 09:55 UTC by deathaxe

This PR ...

1. adds _Git Formats/Git Merge.sublime-settings_ with **simple and restrictive** patterns for git conflict markers.

   They explicitly do not push contexts to avoid interfering with interpolations or any other advanced syntax features.

2. includes those patterns as sort of comments in all syntax bundled definitions.

   Comments are included in most contexts in all syntax definitions, thus conflict markers should be matched properly with high chances as well.
   
3. includes merge conflict patterns into known multi-line strings or heredocs.

![grafik](https://github.com/user-attachments/assets/26aa3202-b14d-439b-926a-110b1f105b4a)

#### Goals

1. improve UX when using ST as git merge tool
3. reduce risk of badly breaking syntax highlighting due to conflict markers

#### Motivation

1. This PR was created as possible fix/workaround for https://github.com/sublimehq/sublime_text/issues/6498, which is caused by git merge conflict markers, but applies to all syntax definitions. It is therefore a possible alternative for #4046, assuming there are no other "invalid syntax" scenarios, which can break JSX/TSX in such bad ways.
2. Git is a rather common tool these days, and ST can be used as an editor to edit commit messages or resolve conflicts. As such, git conflict markers shouldn't break syntax highlighting or even cause crashes or deadlocks.
4. various linters/tools, such as JSX/TSX language servers also detect git conflict markers and highlight them, most likely to avoid same kind of issues we see with regards to confusing syntax engine.

#### Remarks

1. With this PR all syntax definitions depend on _Git Merge.sublime-syntax_ and thus require _Git Formats_ package to be enabled.

   Pro: Single file to maintain, simple re-usable context for all syntaxes
   
   Contra: inter-package dependency
   
   Alternative: duplicate `conflict` context into all (about 40) syntax definitions :/

2. Initial state of this PR provides a "works in most cases" quality based on existing comments/strings contexts. There may be some situations left, in which conflict markers are not yet detected. Support can however easily be improved in future.

3. Some syntaxes such as Markdown use `===` to highlight headings, which still may cause syntax highlighting issues caused by unavoidable ambiguities. So this PR can provide "the base we can" quality.

2024-09-29 17:35 UTC, michaelblyons commented
I have some thoughts, not in any order, nor necessarily exhaustive:

1. If Git is disabled, I expect the matches just don't show up. It's not catastrophic, right?
2. I like the concept. I have a minimal "Conflict" syntax lying around somewhere with `markup.line.(inserted|deleted)`, which is probably mostly obsolete with this change. 
3. In case it's not obvious to everyone, this can result in mismatched context start/end, but that was already happening anyway.
4. If this is well-received, we should also support `|||||` for `diff3` markers.
5. This is a great example of how injections would be helpful as a core feature.

2024-09-29 18:02 UTC, deathaxe commented
> If Git is disabled, I expect the matches just don't show up. It's not catastrophic, right?

The only downside would be console messages about "no such context".

> In case it's not obvious to everyone, this can result in mismatched context start/end, but that was already happening anyway.




    If this is well-received, we should also support ||||| for diff3 markers.

> This is a great example of how injections would be helpful as a core feature.

2024-09-29 18:13 UTC, deathaxe commented
An alternative location for the Merge syntax would be within _Text_ package, which if disabled causes lots of trouble anyway and is thus less likely to be.

This would be justified by conflict markers not being limited to git, but rather being a common unix convention, with regards to `diff3`.

2024-09-29 18:39 UTC, michaelblyons commented
> by the way ours/theirs is interrupting normal source code.

Yes, that's what I mean.  Agreed that it can't be helped.

```
<<<<<
func foo (bar) {
=====
func foo (bar, baz) {
>>>>>
// Extra nesting
```

2024-10-04 13:09 UTC, deathaxe commented
Still UX is way better then with most syntaxes highlighting those markers as operators, tag punctuation or even illegal.

2024-10-05 10:07 UTC, deathaxe commented
1. Renamed scopes to original unix `diff3` scope as those markers are not tight to git.
2. moved it to _Text_ package to always be available.

Ideally _Diff_ package seems the more suitable target, but it is not included in Sublime Merge and could also be disabled like _Git Formats_.

2024-10-25 15:53 UTC, deathaxe commented
Moved Diff3.sublime-syntax into _Diff_ package as it finally feels misplaced in _Text_ package.

@dpjohnst : As Diff3 is included by all other syntaxes, _Diff_ package needs to be shipped with Sublime Merge, once this PR gets merged.

2024-10-25 16:02 UTC, michaelblyons commented
> Moved Diff3.sublime-syntax into _Diff_ package as it finally feels misplaced in _Text_ package.

Good. I thought about recommending this, and forgot to post.

If I were doing this, I'd make the syntax a functional one called `Diff/Conflict.sublime-syntax` and have markup add/remove sections in between the conflict markers. (Unsure what to use for the Diff3 common base. I personally use comment for those, but I could see markup modified as another possibility.) You can still grab just the marker contexts for your injection into the other syntaxes.

2024-10-25 16:27 UTC, deathaxe commented
Name "Diff3" is inspired by the original unix tool producing output with such tags, like unix tool "diff" produces output with syntax "Diff".

Renaming it to _Conflict.sublime-syntax_ would mean to remove reference to diff3, which I don't find ideal.

Context `conflicts` exists to be able to add more diff3 specific rules, which are not of interest in other syntaxes. I haven't checked if that will be required though.

We could otherwise follow Diff.sublime-syntax and just put everything in `main`. I currently don't see reasons to add each pattern into a dedicated context as they are always required together and chances they need to be overridden individually seem rather low.

`markup` scope is somewhat inspired by Markdown, which scopes most such special things that way. That scope is also rather uncommon in normal source code and thus may provide prominent enough highlighting to clearly stand out from the rest.

Scoping it `comment` would be as correct though.

2024-10-25 16:35 UTC, michaelblyons commented
How about `Diff3 Conflict.sublime-syntax`, then? The reason I'm shy about calling it `Diff3.sublime-syntax` is that the "normal" Diff3 output [looks very different](https://www.gnu.org/software/diffutils/manual/diffutils.html#Example-diff3-Normal) from that.

2024-10-25 16:45 UTC, deathaxe commented
How about adding support for normal output?

2024-10-25 17:21 UTC, michaelblyons commented
That might work. IIRC, one of the (three) `diff3` output modes has a conflict with one kind of normal `diff` output, but they might not conflict with each other. It might be possible to bundle all three `diff3` output styles into a single syntax.

2024-10-25 17:43 UTC, deathaxe commented
Well, I'd probably start with normal output mode.

I have no strong meaning about scope names - just explained their origin.

With a look at Diff we could also use `meta.separator punctuation.definition.separator` for `<<<<<` etc.

Anything which allows them to be uniquely addressed by color schemes might be ok. The question is what defaults we prefer. Should they appear like comments in the first place or just like plain text (which Mariana/Monokai) highlight them, currently.

Another question arises. Diff uses `source.diff`. Should we therefore change main scope to `source.diff3`?

2024-10-25 18:10 UTC, michaelblyons commented
> With a look at Diff we could also use `meta.separator punctuation.definition.separator` for `<<<<<` etc.

I'm opposed. I think the scope you already chose is the right one, and Diff should change to match.

> Anything which allows them to be uniquely addressed by color schemes might be ok. The question is what defaults we prefer. Should they appear like comments in the first place or just like plain text (which Mariana/Monokai) highlight them, currently.

Oh, the conflict markers? I would not use `comment`. I think your original `punctuation.section` is correct, as I said above.

I was only talking about if a simple syntax is made whose `main` highlights Diff3 conflicts, not the injection of conflict markers into complicated source code.

```
octopus
<<<<< a
tiger
whale
\^^^^^ markup.line.deleted
|||||
koala
\^^^^^ ???? not sure if `comment` or `markup.line.modified`
=====
elephant
\^^^^^^^^ markup.line.inserted
>>>>>
```

> Another question arises. Diff uses `source.diff`. Should we therefore change main scope to `source.diff3`?

Seems fine. No strong opinions. I've changed my mind on this a bunch of times with no obvious right answer.

2025-02-13 16:40 UTC, michaelblyons commented
This may have interesting application for [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter) and something modeled after [Git Conflict Resolver](https://packagecontrol.io/packages/Git%20Conflict%20Resolver).

2025-02-14 07:40 UTC, deathaxe commented
I'll revicit this PR once #4111 is merged.

2025-02-24 20:34 UTC, deathaxe commented
Rebased branch and tweaked syntaxes to use _Diff/Diff.sublime-syntax#conflict-markers_.

Yet question remains, whether it is a good idea to create such massive cross package depenedency.

2025-02-24 20:39 UTC, michaelblyons requested changes
I also thought I saw a Git Formats tmPreferences file that I was going to suggest moving to Diff, but it seems to be gone now.

2025-02-24 20:39 UTC, michaelblyons commented on OCaml/OCamllex.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  match-patterns:
Mis-paste

2025-02-24 20:39 UTC, michaelblyons commented on OCaml/OCamlyacc.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  declaration-matches:
Mis-paste

2025-02-24 20:39 UTC, michaelblyons commented on RestructuredText/syntax_test_restructuredtext.rst
> +
Did you leave out `========` intentionally?

2025-02-24 20:39 UTC, michaelblyons commented on Rust/tests/syntax_test_conflicts.rs
> +)
Add trailing newline?

2025-02-24 20:48 UTC, deathaxe commented
> I also thought I saw a Git Formats tmPreferences file

Yeah, I can always look at PRs for hours and a second after hitting push, I find something.

2025-02-24 20:49 UTC, deathaxe commented on RestructuredText/syntax_test_restructuredtext.rst
> +
This is one of the ambiguities we are facing in RST and MD. 

This line is already tested as part of a heading in line 48.

2025-02-24 20:52 UTC, deathaxe commented on OCaml/OCamlyacc.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  declaration-matches:
Nope, it should be following block comments. Maybe just missing another one in quoted docstrings.

2025-02-24 20:57 UTC, deathaxe commented on OCaml/OCamllex.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  match-patterns:
Also valid here.

2025-02-24 21:13 UTC, michaelblyons submitted a review, later dismissed
Added more context on the OCaml thing I flagged.

2025-02-24 21:13 UTC, michaelblyons commented on OCaml/OCamlyacc.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  declaration-matches:
Why is `declaration-matches` part of the comment? (And before your more recent push, it no longer a context.)

2025-02-24 21:13 UTC, michaelblyons commented on OCaml/OCamllex.sublime-syntax
> +        - include: scope:source.diff#conflict-markers  # merge conflict marker  match-patterns:
Why is `match-patterns:` part of this line comment?

2025-02-24 21:13 UTC, michaelblyons commented on OCaml/OCaml.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  constants:
Why is `constants:` in the comment here?

2025-02-24 21:24 UTC, deathaxe commented on OCaml/OCamllex.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  match-patterns:
I see.

2025-02-24 21:27 UTC, deathaxe commented on OCaml/OCamlyacc.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  declaration-matches:
Maybe some multi-cursor edit or issue with unproper use of "Find in Files", not sure.

2025-02-24 21:30 UTC, deathaxe commented on OCaml/OCamllex.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  match-patterns:
Fixed.

2025-02-24 21:30 UTC, deathaxe commented on OCaml/OCamlyacc.sublime-syntax
> +    - include: scope:source.diff#conflict-markers  # merge conflict marker  declaration-matches:
Fixed

2025-02-24 21:47 UTC, michaelblyons commented on OCaml/OCamllex.sublime-syntax
> +        - include: scope:source.diff#conflict-markers  # merge conflict marker  match-patterns:
This one is still here.

2025-02-25 09:34 UTC, michaelblyons reviewed
Switching from "changes requested" to neutral. I think this is a reasonable change, but I would like to hear from others before approving.

2025-04-19 08:02 UTC, deathaxe commented
With regards to how shebang is implemented, I tend to think conflict marker contexts should also be implemented individually for each syntax to avoid cross-package dependencies, especially as Diff is not part of Sublime Merge.

2025-04-19 09:58 UTC, deathaxe commented
If someone finds unhandled multi-line strings in a syntax, feel free to report it.

Otherwise with dependencies to Diff.sublime-syntax being removed, this PR should be ready.

2025-04-19 19:36 UTC, deathaxe commented
Folding would only make sense if ours/theirs/base parts could be folded individually. With `base` part being optional syntax, a begin/end may be missing, causing everything being folded.

It's also not quite sure how it interferes with syntaxes' own folding rules.

Hence I'd hesitate to "just" add some rules for it.

2025-04-30 07:46 UTC, deathaxe commented
FWIW, it even makes a difference in Sublime Merge...

![grafik](https://github.com/user-attachments/assets/c59fcd5e-4795-4d76-9d1b-dae8427ec4a1)

2025-05-01 11:56 UTC, michaelblyons approved these changes

2025-05-01 20:12 UTC, merged

2025-05-01 20:12 UTC, deathaxe commented
Cool!